development:
  adapter: postgresql
  encoding: unicode
  database: adquick_development
  username:
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: adquick_test
  username:
  port: 5432

staging:
  adapter: postgresql

production:
  adapter: postgresql
